- name: Setup Miniconda
  uses: conda-incubator/setup-miniconda@v2
  with:
    auto-update-conda: true
    python-version: 3.9
    activate-environment: lista-links
    environment-file: environment.yml
    use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
- name: Install dependencies
  shell: bash -l {0}
  run: |
    conda info -v # mostra informações sobre o conda e o ambiente
    conda list -v # mostra a lista de pacotes instalados
    conda install -v -y --file requirements.txt # instala as dependências com mais detalhes
